
<table class="table">

    <tr>
      <th><?= LABEL_STUDENTS_BIRTHDAY_AT ?></th>
      <td>
          <?= $this->student->formInput('birthday_at', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_STUDENTS_CODE ?></th>
      <td>
          <?= $this->student->formInput('code', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_STUDENTS_FIRST_NAME ?></th>
      <td>
          <?= $this->student->formInput('first_name', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_STUDENTS_FIRST_NAME_KANA ?></th>
      <td>
          <?= $this->student->formInput('first_name_kana', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_STUDENTS_LAST_NAME ?></th>
      <td>
          <?= $this->student->formInput('last_name', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_STUDENTS_LAST_NAME_KANA ?></th>
      <td>
          <?= $this->student->formInput('last_name_kana', ['class' => 'form-control']) ?>
      </td>
    </tr>

</table>

            