<div class="card">
  <h2 class="card-header">urlFor($controller, $action, $id, $http_params) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <a href="<?= $this->urlFor(['controller' => 'sample', 'action' => 'edit', 'id' => 1], ['key' => 'param1']) ?>">edit</a>
    <h3>code</h3>
    <div>
      $this->urlFor(['controller' => 'sample', 'action' => 'edit', 'id' => 1], ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlFor(['controller' => 'sample', 'action' => 'edit', 'id' => 1], ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkTo([$controller, $action = null, $id = null, $params = null) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <?= $this->linkTo(['controller' => 'sample', 'action' => 'action', 'id' => 1], ['label' => 'sample', 'class' => 'btn btn-primary',  'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkTo(['controller' => 'sample', 'action' => 'action', 'id' => 1], ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkTo(['controller' => 'sample', 'action' => 'action', 'id' => 1], ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">redirectTo([$action = null, $id = null], $params = null) : void</h2>

  <div class="card-block">
    <h3>code</h3>
    <div>
      $this->redirectTo(['action' => 'action', 'id' => 1], ['key' => 'param1'])
    </div>
  </div>
</div>

<div class="card">
    <h2 class="card-header">updateSort($model_name = null, $is_json = true): void</h2>
  
    <div class="card-block">
      <h3>summary</h3>
      if Model file for Entity class exists, update sort on 'sort_order' column by $_REQUEST['sort_order'] (= array of primary id).
      <h3>code</h3>
      <div>
        <h4>before</h4>
        <pre>
        $values[] = ['name' => 'Japan', 'sort_order' => 1];
        $values[] = ['name' => 'USA', 'sort_order' => 2];
        $values[] = ['name' => 'France', 'sort_order' => 3];
        $values[] = ['name' => 'Italy', 'sort_order' => 4];

        DB::table('Country')->inserts($values); //DB inserts
        </pre>
        <h4>after</h4>
        <pre>
        $_REQUEST['sort_order'] = [
              ['id'=> 1, 'order' => 2],
              ['id'=> 2, 'order' => 1],
              ['id'=> 3, 'order' => 4],
              ['id'=> 4, 'order' => 3]
            ]
        $this->updateSort('Country', false);
    
        $country = DB::table('Country');
        $country->all();
        var_export($country->values);

        array (
          0 => 
          array (
            'id' => 2,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => '2018-06-19 17:21:02',
            'sort_order' => 0,
            'name' => 'USA',
          ),
          1 => 
          array (
            'id' => 1,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => NULL,
            'sort_order' => 1,
            'name' => 'Japan',
          ),
          2 => 
          array (
            'id' => 4,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => '2018-06-19 17:21:02',
            'sort_order' => 2,
            'name' => 'Italy',
          ),
          3 => 
          array (
            'id' => 3,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => NULL,
            'sort_order' => 3,
            'name' => 'France',
          ),
        )
        </pre>
      </div>
    </div>
  </div>