<div class="card">
  <h2 class="card-header">urlFor($controller, $action, $id, $http_params) : string</h2>

  <div class="card-block">
    <a href="<?= $this->urlFor('sample', 'action', 1, ['key' => 'param1']) ?>">Action</a>
    <h3>code</h3>
    <div>
      $this->urlFor('sample', 'action', 1, ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlFor('sample', 'action', 1, ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlControllerFor($controller, $http_params) : string</h2>

  <div class="card-block">
    <a href="<?= $this->urlControllerFor('sample', ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlControllerFor('sample', ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlControllerFor('sample', ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlActionFor($action, $http_params) : string</h2>

  <div class="card-block">
    <a href="<?= $this->urlActionFor('action', ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlActionFor('action', ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlActionFor('action', ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlSelfFor($action, $id, $http_params) : string</h2>

  <div class="card-block">
    <a href="<?= $this->urlSelfFor('action', 1, ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlSelfFor('action', 1, ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlSelfFor('action', 1, ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkTag($controller, $action = null, $id = null, $params = null) : string</h2>

  <div class="card-block">
    <?= $this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary',  'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkControllerTag($controller, $params = null) : string</h2>

  <div class="card-block">
    <?= $this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkActionTag($action = null, $id = null, $params = null) : string</h2>

  <div class="card-block">
    <?= $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
    <h2 class="card-header">redirectTo($action = null, $id = null, $params = null) : string</h2>
  
    <div class="card-block">
      <?= $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']]) ?>
      <h3>code</h3>
      <div>
        $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
      </div>
      <h3>result</h3>
      <div>
        <?= htmlspecialchars($this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
      </div>
    </div>
  </div>
