<div class="card">
  <h2 class="card-header">urlFor($controller, $action, $id, $http_params) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <a href="<?= $this->urlFor('sample', 'action', 1, ['key' => 'param1']) ?>">Action</a>
    <h3>code</h3>
    <div>
      $this->urlFor('sample', 'action', 1, ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlFor('sample', 'action', 1, ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlControllerFor($controller, $http_params) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <a href="<?= $this->urlControllerFor('sample', ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlControllerFor('sample', ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlControllerFor('sample', ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlActionFor($action, $http_params) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <a href="<?= $this->urlActionFor('action', ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlActionFor('action', ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlActionFor('action', ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">urlSelfFor($action, $id, $http_params) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <a href="<?= $this->urlSelfFor('action', 1, ['key' => 'param1']) ?>">Sample</a>
    <h3>code</h3>
    <div>
      $this->urlSelfFor('action', 1, ['key' => 'param1'])
    </div>
    <h3>result</h3>
    <div>
      <?= $this->urlSelfFor('action', 1, ['key' => 'param1']) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkTag($controller, $action = null, $id = null, $params = null) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <?= $this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary',  'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkTag('sample', 'action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkControllerTag($controller, $params = null) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <?= $this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkControllerTag('sample', ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">linkActionTag($action = null, $id = null, $params = null) : string</h2>

  <div class="card-block">
    <h3>sample</h3>
    <?= $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']]) ?>
    <h3>code</h3>
    <div>
      $this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])
    </div>
    <h3>result</h3>
    <div>
      <?= htmlspecialchars($this->linkActionTag('action', 1, ['label' => 'sample', 'class' => 'btn btn-primary', 'http_params' => ['key' => 'param1']])) ?>
    </div>
  </div>
</div>

<div class="card">
  <h2 class="card-header">redirectTo($action = null, $id = null, $params = null) : void</h2>

  <div class="card-block">
    <h3>code</h3>
    <div>
      $this->redirectTo('action', 1, ['key' => 'param1'])
    </div>
  </div>
</div>

<div class="card">
    <h2 class="card-header">updateSort($model_name = null, $is_json = true): void</h2>
  
    <div class="card-block">
      <h3>summary</h3>
      if Model file for Entity class exists, update sort on 'sort_order' column by $_REQUEST['sort_order'] (= array of primary id).
      <h3>code</h3>
      <div>
        <h4>before</h4>
        <pre>
        $values[] = ['name' => 'Japan', 'sort_order' => 1];
        $values[] = ['name' => 'USA', 'sort_order' => 2];
        $values[] = ['name' => 'France', 'sort_order' => 3];
        $values[] = ['name' => 'Italy', 'sort_order' => 4];

        DB::table('Country')->inserts($values); //DB inserts
        </pre>
        <h4>after</h4>
        <pre>
        $_REQUEST['sort_order'] = [2, 1, 4, 3]; //primary id

        $this->updateSort('Country', false);
    
        $country = DB::table('Country');
        $country->all();
        var_export($country->values);

        array (
          0 => 
          array (
            'id' => 2,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => '2018-06-19 17:21:02',
            'sort_order' => 0,
            'name' => 'USA',
          ),
          1 => 
          array (
            'id' => 1,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => NULL,
            'sort_order' => 1,
            'name' => 'Japan',
          ),
          2 => 
          array (
            'id' => 4,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => '2018-06-19 17:21:02',
            'sort_order' => 2,
            'name' => 'Italy',
          ),
          3 => 
          array (
            'id' => 3,
            'created_at' => '2018-06-19 17:20:38',
            'updated_at' => NULL,
            'sort_order' => 3,
            'name' => 'France',
          ),
        )
        </pre>
      </div>
    </div>
  </div>