<h1>PgsqlEntity Basic functions</h1>
<div class="card">
  <h2 class="card-header">pgVersion() : array</h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$results = DB::model('Country')->pgVersion();
    </pre>
    <h4>Result</h4>
    <pre>
array (
  'client' => '10.3 (Debian 10.3-2)',
  'protocol' => 3,
  'server' => '9.5.12',
  'server_encoding' => 'UTF8',
  'client_encoding' => 'UTF8',
  'is_superuser' => 'on',
  'session_authorization' => 'postgres',
  'DateStyle' => 'ISO, MDY',
  'IntervalStyle' => 'postgres',
  'TimeZone' => 'Japan',
  'integer_datetimes' => 'on',
  'standard_conforming_strings' => 'on',
  'application_name' => '',
)
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">createDatabase() : PgsqlEntity</h2>
  <div class="card-block">
    <span class="badge badge-danger">need shell command 'createdb' authority</span>
    <h4>code</h4>
    <pre>
$pgsql = new PgsqlEntity();
$results = $pgsql->createDatabase();
    </pre>
    <h4>SQL</h4>
    <pre>
array (
  'cmd' => 'createdb -U postgres -E UTF8 --host localhost --port 5432 sample 2>&1',
  'output' => 
  array (
    0 => 'createdb: database creation failed: ERROR:  database "sample" already exists',
  ),
  'return' => 1,
)
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">all() : PgsqlEntity</h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->all();

//instance bind $values: array
$country->values;
</pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries;
</pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">fetch($id) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->fetch(1);

//instance bind $value: array list
$country->value;
</pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE id = 1;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">find($id) : PgsqlEntity</h2>
  <div class="card-block">
    same function : fetch($id)
  </div>
</div>

<div class="card">
  <h2 class="card-header">select($params = null) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->select(['name'])->fetch(1);
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT name FROM countries WHERE id = 1;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">fetch($id) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->where('area', 'Asia')->one();

//instance bind $value: array list
$country->value;
</pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE area = \'Asia\';
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">where($condition, $value = null, $eq = '=') : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
//param1 only
$country = DB::model('Country')->where("area = 'Asia'")->all();

//param1 & param2
$country = DB::model('Country')->where('area', 'Asia')->all();

//param1 & param2 & param3
$country = DB::model('Country')->where('area', 'Asia', '=')->all();
  </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE area = 'Asia' ORDER BY countries.sort_order;

//not exists 'sort_order' column
SELECT * FROM countries WHERE area = 'Asia'; 
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">wheres($conditions) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$conditions[] = "name = 'Japan'";
$conditions[] = "area = 'Asia'";
$country = DB::model('Country')->wheres($conditions)->all();
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE name = 'Japan' AND area = 'Asia' ORDER BY countries.sort_order;

//not exists 'sort_order' column
SELECT * FROM countries WHERE name = 'Japan' AND area = 'Asia'; 
      </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">whereIn($column, $values) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$values = [1, 3, 4];

$country = DB::model('Country')->whereIn('id', $values)->all();
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE id in (1, 3, 4) ORDER BY countries.sort_order;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">insert($posts) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->insert(['name' => 'Japan']);
  </pre>
    <h4>SQL</h4>
    <pre>
INSERT INTO countries (created_at,name,area,is_provide,sort_order,updated_at) VALUES (current_timestamp,\'Japan\',NULL,NULL,NULL,NULL);SELECT lastval();
  </pre>
  </div>
</div>


<div class="card">
  <h2 class="card-header">inserts($posts) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$values[] = ['name' => 'USA', 'sort_order' => 2];
$values[] = ['name' => 'France', 'sort_order' => 3];
$values[] = ['name' => 'Italy', 'sort_order' => 4];
$values[] = ['name' => 'China', 'sort_order' => 5];

$country = DB::model('Country')->inserts($posts);
  </pre>
    <h4>SQL</h4>
    <pre>
INSERT INTO countries (created_at, name, area, is_provide, sort_order, updated_at) VALUES 
  (current_timestamp, \'USA\', NULL, NULL, \'2\', NULL), 
  (current_timestamp, \'France\', NULL, NULL, \'3\', NULL), 
  (current_timestamp, \'Italy\', NULL, NULL, \'4\', NULL)
  (current_timestamp, \'China\', NULL, NULL, \'5\', NULL), 
  </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">update($posts, $id) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->update(['area' => 'Asia'], 1);
    </pre>
    <h4>SQL</h4>
    <pre>
UPDATE countries SET area = \'Asia\',updated_at = current_timestamp WHERE id = 1;
    </pre>
  </div>
</div>


<div class="card">
  <h2 class="card-header">upsert($posts) : PgsqlEntity <span class="badge badge-danger"> PostgreSQL 9.5 >=</span></h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country');
$country->setUpsertConstraint('countries_name_key');
$country->upsert(['name' => 'Japan', 'is_provide' => true]);
    </pre>
    <h4>SQL</h4>
    <pre>
INSERT INTO countries (created_at,name,area,is_provide,sort_order,updated_at) 
    VALUES (current_timestamp,'Japan',NULL,TRUE,NULL,NULL) 
    ON CONFLICT ON CONSTRAINT countries_name_key 
    DO UPDATE SET name = 'Japan', is_provide = TRUE, updated_at = current_timestamp
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">delete($id) : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->delete(4);
  </pre>
    <h4>SQL</h4>
    <pre>
DELETE FROM countries  WHERE id = 5;
  </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">deletes() : PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->deletes();
    </pre>
    <h4>SQL</h4>
    <pre>
DELETE FROM countries;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">order($column, $option = null) : integer</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$count = DB::model('Country')->order('name')->all();
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries ORDER BY countries.name;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">count($column = null): PgsqlEntity</h2>

  <div class="card-block">
    <h4>code</h4>
    <pre>
$count = DB::model('Country')->count('name');
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries ORDER BY countries.name;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">relation($model_name, $foreign_key = null, $value_key = null)): PgsqlEntity</h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$country = DB::model('Country')->fetch(1);

//param1 only
$user = $country->relation('User')->all();

//add param2 & param3
$user = $country->relation('User', 'country_id', 'id')->all();
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM countries WHERE id = 1;
SELECT * FROM users WHERE country_id = '1' ORDER BY users.sort_order
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">belongsTo($model_name, $foreign_key = null, $value_key = null)): PgsqlEntity</h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$user = DB::model('User')->fetch(5);
$country = $user->belongsTo('Country');
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM users WHERE id = 5;
SELECT * FROM countries WHERE id = 3;
    </pre>
  </div>
</div>

<div class="card">
  <h2 class="card-header">bindBelongsTo($model_name, $foreign_key = null, $value_key = null)): PgsqlEntity</h2>
  <div class="card-block">
    <h4>code</h4>
    <pre>
$user = DB::model('User')->fetch(5)->bindBelongsTo('Country');

//bind
$user->country->value;
    </pre>
    <h4>SQL</h4>
    <pre>
SELECT * FROM users WHERE id = 5;
SELECT * FROM countries WHERE id = 3;
    </pre>
  </div>
</div>