<h1>PwTableDND.js</h1>

<h2>Sample</h2>
  <a class="pw_table_dnd btn btn-outline-primary" event="click" action="edit">Edit</a>
  <a class="pw_table_dnd pw-tablednd-menu btn btn-outline-primary" event="click" action="update_sort" style="display: none">Update</a>
  <a class="pw_table_dnd pw-tablednd-menu btn btn-outline-primary" event="click" action="reset" style="display: none">Close</a>

<table id="sortable-table" class="table">
  <thead>
    <tr>
      <th>No</th>
      <th>City</th>
    </tr>
  </thead>
  <tr row-id="1">
    <td>1</td>
    <td>Tokyo</td>
  </tr>
  <tr row-id="2">
    <td>2</td>
    <td>New York</td>
  </tr>
  <tr row-id="3">
    <td>3</td>
    <td>Paris</td>
  </tr>
  <tr row-id="4">
    <td>4</td>
    <td>London</td>
  </tr>
</table>

<h2>Result</h2>
<div id="result">

</div>

<h2></h2>
<h3>(1) load PwTableDND.js</h3>
<div>
  <ul>
    <li>javascripts/lib/PwNode.js</li>
    <li>javascripts/lib/PwTableDND.js</li>
  </ul>
</div>
<h3>(2) set params for PwTableDND.js</h3>
<div>
  <pre>
      pw_table_dnd = new PwTableDND(
        {
          url: '',
          table_id: 'sortable-table',
          row_id_column: 'row-id',
          is_show_up: true,
          is_show_down: true,
          drag_label: '[=]',
          top_label: '[T]',
          bottom_label: '[B]',
          is_font_awesome: false
        }
      );
      pw_table_dnd.edit();
  </pre>
</div>

<h3>(3) table tag: Set id on table.(default: sortable-table) & tr attribute is 'row-id="number"'</h3>
<div>
  <pre>
<?= htmlspecialchars('
<table id="sortable-table">
  <thead>
    <tr>
      <th>No</th>
      <th>City</th>
    </tr>
  </thead>
  <tr row-id="1">
    <td>1</td>
    <td>Tokyo</td>
  </tr>
  <tr row-id="2">
    <td>2</td>
    <td>New York</td>
  </tr>
</table>
')
?>
  </pre>
</div>

<h3>(5) As control HTML tag, Write class="pw_table_dnd".</h3>
<div>
  <pre>
<?= htmlspecialchars('
<a class="pw_table_dnd" event="click" action="edit">Edit</a>
<a class="pw_table_dnd pw-tablednd-menu" event="click" action="update_sort">Update</a>
<a class="pw_table_dnd pw-tablednd-menu" event="click" action="reset">Close</a>
')
?>
  </pre>
</div>
<div>
  <h4>Change mode sortable</h4>
  <ul>
    <li>class="pw-lib"</li>
    <li>pw-lib="PwSortable"</li>
    <li>pw-action="edit"</li>
  </ul>

  <h4>Save sort_order</h4>
  <ul>
    <li>class="pw-lib"</li>
    <li>pw-lib="PwSortable"</li>
    <li>pw-action="update_sort"</li>
  </ul>

  <h4>Reset sort_order</h4>
  <ul>
    <li>class="pw-lib"</li>
    <li>pw-lib="PwSortable"</li>
    <li>pw-action="reset"</li>
  </ul>
</div>

<h3>(7) Request automatically JSON to server (method = POST), when click on tag 'pw-action="update_sort"'</h3>

<h3>(8) Reseive JSON from server.</h3>

<h2>HTML Source</h2>
<pre>
<?= htmlspecialchars('
<script type="text/javascript" src="../../javascripts/lib/PwController.js"></script>
<script type="text/javascript" src="../../javascripts/lib/PwNode.js"></script>
<script type="text/javascript" src="../../javascripts/lib/PwSortable.js"></script>

<a href="#" class="btn btn-outline-primary pw-lib" pw-lib="PwSortable" pw-action="edit"><i class="fa fa-sort"></i>Order</a>
<a href="#" class="btn btn-primary pw-lib pw-sortable-control" pw-lib="PwSortable" pw-controller="sample" pw-action="update_sort" style="display: none"><i class="fa fa-save"></i>Save</a>
<a href="#" class="btn btn-outline-primary pw-lib pw-sortable-control" pw-lib="PwSortable" pw-action="reset" style="display: none"><i class="fa fa-times"></i>Reset</a>

<table id="sortable-table" class="table">
  <thead>
    <tr>
      <th>No</th>
      <th>City</th>
    </tr>
  </thead>

  <tr row-id="1">
    <td>1</td>
    <td>Tokyo</td>
  </tr>
  <tr row-id="2">
    <td>2</td>
    <td>New York</td>
  </tr>
  <tr row-id="3">
    <td>3</td>
    <td>Paris</td>
  </tr>
  <tr row-id="4">
    <td>4</td>
    <td>London</td>
  </tr>
</table>
    ');
  ?>
</pre>

<h2>JavaScript Source</h2>
<pre>
  pw_table_dnd = new PwTableDND(
    {
      url: '',
      table_id: 'sortable-table',
      row_id_column: 'row-id',
      is_show_up: true,
      is_show_down: true,
      drag_label: '[=]',
      top_label: '[T]',
      bottom_label: '[B]',
      is_font_awesome: false
    }
  );
  pw_table_dnd.edit();
</pre>

<script>
  pw_table_dnd = new PwTableDND(
    {
      url: '',
      table_id: 'sortable-table',
      row_id_column: 'row-id',
      is_show_up: true,
      is_show_down: true,
      drag_label: '[=]',
      top_label: '[T]',
      bottom_label: '[B]',
      is_font_awesome: false
    }
  );
  pw_table_dnd.edit();
</script>