
<form action="<?= url_for('update') ?>" method="post">
  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_MAIL ?></label>
    <input class="form-control" type="text" name="user[email]" value="<?= $this->user->value['email'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_LAST_NAME ?></label>
    <input class="form-control" type="text" name="user[last_name_kana]" value="<?= $this->user->value['last_name_kana'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_FIRST_NAME ?></label>
    <input class="form-control" type="text" name="user[first_name_kana]" value="<?= $this->user->value['first_name_kana'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_LAST_NAME ?></label>
    <input class="form-control" type="text" name="user[last_name]" value="<?= $this->user->value['last_name'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_FIRST_NAME ?></label>
    <input class="form-control" type="text" name="user[first_name]" value="<?= $this->user->value['first_name'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_BIRTHDAY ?></label>
    <?= $this->user->formSelectDate('birthday_at', ['formatter' => 'j']); ?>
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_GENDER ?></label>
    <?= $this->user->formRadio('gender', ['csv' => 'gender']) ?>
  </div>

  <div class="text-center">
    <?= FormHelper::submit(LABEL_UPDATE) ?>
    <?= FormHelper::linkButton('user/', LABEL_BACK) ?>
  </div>
</div>
</form>
