<form class="form-signin" method="post" action="<?= url_for('user/auth') ?>">
  <div class="card">
    <div class="card-header">
      <?= LABEL_LOGIN ?>
    </div>
    <div class="card-block">
      <p id="profile-name" class="profile-name-card"></p>
      <?= $this->user->formInput('email') ?>
      <?= $this->user->formPassword('password') ?>
    </div>
    <div class="card-footer">
      <?= FormHelper::submit(LABEL_LOGIN) ?>
    </div>
  </div>
</form>

<a class="btn btn-secondary" href="<?= url_for('regist/')  ?>"><?= LABEL_REGIST ?></a>
