
<div class="hero-unit">

  <h1>Hello, <?= APP_NAME ?>!</h1>

  build with <a href="https://v4-alpha.getbootstrap.com/" target="_blank">Bootstrap4</a>

  <div>
    <h2>Sample</h2>
    <a href="<?= $this->urlFor(['controller' => 'sample']) ?>">Sample</a>
  </div>

  <h2>Application Information</h2>
  <table class="table table-auto">
    <tr>
      <th>BASE_DIR</th>
      <td><?= undefineLabel('BASE_DIR', BASE_DIR) ?></td>
    </tr>
    <tr>
      <th>PROJECT_NAME</th>
      <td><?= undefineLabel('PROJECT_NAME', PROJECT_NAME) ?></td>
    </tr>
    <tr>
      <th>PROJECT_DIR</th>
      <td><?= undefineLabel('PROJECT_DIR', PROJECT_DIR) ?></td>
    </tr>
    <tr>
      <th>TMP_DIR</th>
      <td><?= undefineLabel('TMP_DIR', TMP_DIR) ?></td>
    </tr>
    <tr>
      <th>DB_DIR</th>
      <td><?= undefineLabel('DB_DIR', DB_DIR) ?></td>
    </tr>
    <tr>
      <th>DEBUG</th>
      <td><?= undefineLabel('DEBUG', DEBUG) ?></td>
    </tr>
    <tr>
      <th>DB_SETTING_FILE</th>
      <td><?= undefineLabel('DB_SETTING_FILE', DB_SETTING_FILE) ?></td>
    </tr>
    <tr>
      <th>MAIL_SETTING_FILE</th>
      <td><?= undefineLabel('MAIL_SETTING_FILE', MAIL_SETTING_FILE) ?></td>
    </tr>
    <tr>
      <th>DEFAULT_LOCALE</th>
      <td><?= undefineLabel('DEFAULT_LOCALE', DEFAULT_LOCALE) ?></td>
    </tr>
  </table>

  <h2>Application Setting</h2>
  <table class="table table-auto">
    <tr>
      <th>file path</th>
      <td><?= BASE_DIR."app/application_setting.php" ?></td>
    </tr>
    <tr>
      <th>APP_NAME</th>
      <td><?= undefineLabel('APP_NAME', APP_NAME) ?></td>
    </tr>
    <tr>
      <th>HTML_TITLE</th>
      <td><?= undefineLabel('HTML_TITLE', HTML_TITLE) ?></td>
    </tr>
    <tr>
      <th>VERSION</th>
      <td><?= undefineLabel('VERSION', VERSION) ?></td>
    </tr>
  </table>

  <h2>PostgreSQL</h2>
  <table class="table table-auto">
    <tr>
      <th>DB_NAME</th>
      <td>
        <?= undefineLabel('DB_NAME', DB_NAME) ?>
      </td>
    </tr>
    <tr>
      <th>DB_HOST</th>
      <td><?= undefineLabel('DB_HOST', DB_HOST) ?></td>
    </tr>
    <tr>
      <th>DB_NAME</th>
      <td><?= undefineLabel('DB_PORT', DB_PORT) ?></td>
    </tr>
    <tr>
      <th>DB_USER</th>
      <td><?= undefineLabel('DB_USER', DB_USER) ?></td>
    </tr>
  </table>

  <h2><a href="<?= $this->urlFor(['action' => 'defined']) ?>">Defined</a></h2>

</div>