
<div class="hero-unit">

  <h1>Hello, ProjectManager!</h1>

  <h2>Application Information</h2>
  <table class="table">
    <tr>
      <th>setting file path</th>
      <td><?= undefineLabel('APP_SETTING_FILE_PATH', APP_SETTING_FILE_PATH) ?></td>
    </tr>
  </table>

  <h2>Application Setting</h2>
  <table class="table">
    <tr>
      <th>file path</th>
      <td><?= BASE_DIR."app/application_setting.php" ?></td>
    </tr>
    <tr>
      <th>APP_NAME</th>
      <td><?= undefineLabel('APP_NAME', APP_NAME) ?></td>
    </tr>
    <tr>
      <th>HTML_TITLE</th>
      <td><?= undefineLabel('HTML_TITLE', HTML_TITLE) ?></td>
    </tr>
    <tr>
      <th>VERSION</th>
      <td><?= undefineLabel('VERSION', VERSION) ?></td>
    </tr>
  </table>

  <h2>PostgreSQL</h2>
  <table class="table">
    <tr>
      <th>PG_INFO</th>
      <td><?= undefineLabel('PG_INFO', PG_INFO) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
      <? if ($this->pg_connection): ?>
      <?= $this->pg_connection ?>
      <? else: ?>
      <?= undefineLabelTag() ?>
      <? endif ?>
      </td>
    </tr>
  </table>
  <form>
  <input class="btn btn-primary" type="submit" name="" value="<?= LABEL_CREATE ?>">
  </form>

  <h2>Defined</h2>
  <? if (is_array($this->defined_constants)): ?>

  <table class="table">
  <? foreach ($this->defined_constants as $key => $defined_constatnt): ?>
  <tr>
    <td><?= $key ?></td>
    <td><?= $defined_constatnt ?></td>
  </tr>
  <? endforeach ?>
  </table>

  <? endif ?>

</div>