<!-- TODO setting -->
<?= PwTag::javascript('jquery/jquery-3.3.1.min') ?>
<?= PwTag::javascript('jquery/jquery-ui.min') ?>
<?= PwTag::javascript('jquery/jquery.tablednd') ?>
<?= PwTag::javascript('jquery/jquery.validate.min') ?>
<?= PwTag::javascript('jquery/loadingoverlay.min') ?>

<?= PwTag::javascript('bootstrap/tether.min') ?>
<?= PwTag::javascript('bootstrap/bootstrap.min') ?>

<script type="text/javascript">
  var pw_project_name = '<?= $this->pw_project_name ?>';
</script>

<?= PwTag::javascript('application') ?>
<?= PwTag::javascript('plugin') ?>
<?= PwTag::javascript('functions') ?>
<?= PwTag::javascript('lib/PwController') ?>
<?= PwTag::javascript('lib/PwNode') ?>
<?= PwTag::javascript('lib/PwSortable') ?>
<?= PwTag::javascript('lib/PwScroller') ?>
<?= PwTag::javascriptController($this->class_name) ?>

<? if ($this->js_controllers): ?>
<? foreach ($this->js_controllers as $js_controller): ?>
<? if ($js_controller != $this->class_name): ?>
<?= PwTag::javascriptController($js_controller) ?>
<? endif ?>
<? endforeach ?>
<? endif ?>
