<!-- TODO setting -->
<?= PwTag::javascript('jquery/jquery-3.3.1.min') ?>
<?= PwTag::javascript('jquery/jquery-ui.min') ?>

<?= PwTag::javascript('bootstrap/tether.min') ?>
<?= PwTag::javascript('bootstrap/bootstrap.min') ?>

<script type="text/javascript">
  var pw_project_name = '<?= $this->pw_project_name ?>';
</script>

<!-- pw lib -->
<?= PwTag::javascript('functions') ?>
<?= PwTag::javascript('lib/PwController') ?>
<?= PwTag::javascript('lib/PwNode') ?>
<?= PwTag::javascript('lib/PwUI') ?>
<?= PwTag::javascript('lib/PwLoadingOverlay') ?>
<?= PwTag::javascript('lib/PwForm') ?>
<?= PwTag::javascript('lib/PwTableDND') ?>
<?= PwTag::javascript('lib/PwDate') ?>
<?= PwTag::javascript('lib/PwModal') ?>
<?= PwTag::javascript('lib/PwScroller') ?>
<?= PwTag::javascript('lib/PwAnimation') ?>
<?= PwTag::javascript('lib/PwLog') ?>

<?= PwTag::javascriptController($this->class_name) ?>

<? if ($this->js_controllers): ?>
<? foreach ($this->js_controllers as $js_controller): ?>
<? if ($js_controller != $this->class_name): ?>
<?= PwTag::javascriptController($js_controller) ?>
<? endif ?>
<? endforeach ?>
<? endif ?>
