<? include('menu.phtml') ?>
<pre class="line-numbers">
  <code class="language-php">
      function action_list()
      {
          //view で利用するには $this でController のインスタンスにしておく
          //Laravel のように ローカル変数を blade に引き渡す関数は原則ない
  
          //SELECT * FROM users WHERE is_active = 'TRUE' ORDER BY users.code LIMIT 10;
          $this->user = new User();
          $this->user->whereTrue('is_active')->limit(10)->order('code')->get();
          //別記述
          //$this->user->where('is_active', 'TRUE')->limit(10)->order('code')->get();
          //$this->user = DB::model('User')->limit(10)->order('code')->get();
  
          //$this->user->values に配列でバインド
          //Laravel のように ローカル変数を blade に引き渡す関数は原則ない
      }
  </code>
</pre>
<? if ($this->user->values): ?>
<table class="table">
  <tr>
    <th>code</th>
    <th>name</th>
  </tr>
  <? foreach ($this->user->values as $value): ?>
  <tr>
    <td><?= $value['code'] ?></td>
    <td><?= $value['name'] ?></td>
  </tr>
  <? endforeach ?>
</table>
<? endif ?>