<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>
</head>
<body>

  <div class="nav">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<?= url_for('/') ?>"><?= APP_NAME ?></a>
      </div>
      <nav class="nav nav-pills flex-column flex-sm-row">

      </nav>
    </div>
  </div>

  <div class="container">

    <?= $this->content_for_layout?>

  </div>

</body>
</html>