<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>
</head>
<body>

  <div class="nav">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<?= url_for('/') ?>"><?= APP_NAME ?></a>
      </div>
      <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlActionFor('index') ?>">Index</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlActionFor('controller') ?>">Controller</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlActionFor('model') ?>">PgsqlEntity(Model)</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlActionFor('form_helper') ?>">FormHelper</a>
      </nav>
    </div>
  </div>

  <div class="container">

    <?= $this->content_for_layout ?>

  </div>

</body>
</html>