<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>
  <?= PwTag::stylesheet('fontawesome/fontawesome-all.min') ?>
  <?=PwTag::stylesheet('prism') ?>
  <?=PwTag::javascript('prism') ?>
</head>
<body>

  <div class="nav">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<?= $this->urlFor(['controller' => 'root']) ?>"><?= APP_NAME ?></a>
      </div>
      <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlFor(['action' => 'index']) ?>">Index</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlFor(['action' => 'ex_controller']) ?>">Controller</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="<?= $this->urlFor(['action' => 'ex_model']) ?>">PwEntity(Model)</a>
      </nav>
    </div>
  </div>

  <div class="container">

    <?= $this->content_for_layout ?>

  </div>

  <? include('views/components/form_delete.phtml') ?>
</body>
</html>